### ISSUE TITLE
Unable to set dialog size

### ISSUE THREAD

**Issue by liyao20190808** [JackJonson/flutter_animated_dialog#1]
When i wrap my widget with a Container， set width or height  is not working，the dialog is always fullscreen
`showAnimatedDialog(
                  context: context,
                  barrierDismissible: true,
                  builder: (BuildContext context) {
                    return  Container(
                      padding: EdgeInsets.all(10.0),
                      width: 200.0,
                      child: FlutterLogo(
                        size: 150.0,
                      ),
                    );
                  },
                  animationType: DialogTransitionType.size,
                  curve: Curves.linear,
                );`

**Comment by Seferi** [comment]
I'm having the same problem. Is there a solution to this?

**Comment by JackJonson** [comment]
Using a 'Center' widget wrap your widget like this : 

`Center(
      child: Material(
        color: Colors.transparent,
        child: Container(
          width: 200,
          height: 200,
          child: ChildWidget()
        )
);`
